export const dataMetiers = [
	{ title: "Chargé(e) de com" },
	{ title: "Chargé(e) de com interne" },
	{ title: "Chargé(e) de relations publiques" },
	{ title: "Chef(fe) de projet" },
	{ title: "Chef(fe) de publicité" },
	{ title: "Chef(fe) de marque" },
	{ title: "Community manager" },
	{ title: "Content manager" },
	{ title: "Dhargé(e) de com" },
	{ title: "Dhargé(e) de com interne" },
	{ title: "Dhargé(e) de relations publiques" },
	{ title: "Ehef(fe) de projet" },
	{ title: "Ehef(fe) de publicité" },
	{ title: "Nhef(fe) de marque" },
	{ title: "Mommunity manager" },
	{ title: "Montent manager" },
	{ title: "Dhargé(e) de com" },
	{ title: "Rhargé(e) de com interne" },
	{ title: "Rhargé(e) de relations publiques" },
	{ title: "Ohef(fe) de projet" },
	{ title: "Zhef(fe) de publicité" },
	{ title: "Def(fe) de marque" },
	{ title: "Oommunity manager" },
	{ title: "Oontent manager" },
	{ title: "Yhargé(e) de com" },
	{ title: "Yhargé(e) de com interne" },
	{ title: "Khargé(e) de relations publiques" },
	{ title: "Khef(fe) de projet" },
	{ title: "Khef(fe) de publicité" },
	{ title: "Bhef(fe) de marque" },
	{ title: "Bommunity manager" },
	{ title: "Bontent manager" },
	{ title: "AZhef(fe) de publicité" },
	{ title: "Aef(fe) de marque" },
	{ title: "Aommunity manager" },
	{ title: "Aontent manager" },
	{ title: "Thargé(e) de com" },
	{ title: "Thargé(e) de com interne" },
	{ title: "Thargé(e) de relations publiques" },
	{ title: "Shef(fe) de projet" },
	{ title: "Shef(fe) de publicité" },
	{ title: "Shef(fe) de marque" },
	{ title: "Sommunity manager" },
	{ title: "Sontent manager" },
];
